// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Pokemon struct {
	ID        int32     `json:"id"`
	TrainerID int32     `json:"trainer_id"`
	Species   string    `json:"species"`
	Nickname  string    `json:"nickname"`
	CreatedAt time.Time `json:"created_at"`
}

type Trainer struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}
